name: event_planning_app
description: A comprehensive event planning mobile application built with Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI Components
  cupertino_icons: ^1.0.2
  
  # Charts and Analytics
  fl_chart: ^0.65.0
  
  # JSON Serialization
  json_annotation: ^4.8.1
  
  # State Management
  provider: ^6.1.1
  
  # Internationalization and Date Formatting
  intl: ^0.19.0
  
  # Image Selection
  image_picker: ^1.0.4
  
  # URL Launching
  url_launcher: ^6.2.1
  
  # HTTP Requests
  http: ^1.1.0
  
  # QR Code Generation
  qr_flutter: ^4.1.0
  
  # Encryption
  encrypt: ^5.0.1
  
  # Local Database
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  
  # JSON code generation
  json_serializable: ^6.7.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
  
  # fonts:
    # - family: Roboto
    #   fonts:
    #     - asset: assets/fonts/Roboto-Regular.ttf
    #     - asset: assets/fonts/Roboto-Bold.ttf
    #       weight: 700